# Generated by Django 5.1.2 on 2025-02-11 18:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='IDReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must be in format MU/YY/XXXXX', regex='^MU/\\d{2}/\\d{5}$')])),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +254XXXXXXXXX', regex='^\\+254\\d{9}$')])),
                ('course', models.CharField(max_length=100)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('police_abstract', models.FileField(help_text='Upload police abstract for lost ID', upload_to='abstracts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Received'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Collection'), ('COLLECTED', 'Collected')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LostID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must be in format MU/YY/XXXXX', regex='^MU/\\d{2}/\\d{5}$')])),
                ('course', models.CharField(max_length=100)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('last_seen_location', models.CharField(max_length=200)),
                ('additional_details', models.TextField(blank=True)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='students_ids/front/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='students_ids/back/')),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to='students_ids/additional/')),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to='students_ids/additional/')),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to='students_ids/additional/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FOUND', 'Found'), ('CLAIMED', 'Claimed')], default='PENDING', max_length=10)),
                ('found_location', models.CharField(blank=True, max_length=200, null=True)),
                ('found_date', models.DateTimeField(blank=True, null=True)),
                ('finder_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_ids', to='mut.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer')], default='MPESA', max_length=10)),
                ('transaction_reference', models.CharField(max_length=50, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('replacement_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mut.idreplacement')),
            ],
        ),
    ]
