# Generated by Django 5.1.2 on 2025-02-11 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostid',
            name='registration_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Registration number must be in format SCXXX/YYYY/YYYY or EDXXX/YYYY/YYYY (e.g., SC211/0530/2022 or ED511/0920/2022)', regex='^(SC|ED)\\d{3}/\\d{4}/\\d{4}$')]),
        ),
    ]
